[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "clingo",
    "numpy",
    "scipy",
    "sympy",
    "pytest",
    "re",
    "statistics",
    "gekko",
    "cProfile",
    "pstats",
]
build-backend = "setuptools.build_meta"