name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        pip install clingo
        pip install numpy
        pip install pytest
        pip install scipy
        pip install .

    - name: Test with pytest
      run: |
        cd test && pytest

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: damianodamianodamiano
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: damianodamianodamiano/pasta:latest
