name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pylint
        pip install clingo
        pip install numpy
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # - name: Lint with flake8
    #   run: |
    #     flake8 . --show-source --statistics --max-line-length=127
    
    # - name: Lint with pylint
    #   run: |
    #     pylint src/pasta --disable=W0311 # disable Bad indentation
    
    - name: Test with pytest
      run: |
        cd test && sh test_all.sh
  
  publish:
    if: github.event_name != 'pull_request' # && (contains(github.ref, 'tag'))
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
  
    - name: Get tag
      run: echo "RELEASE_VERSION=1.0.0"

    - name: Build docker image and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pasta:${{ env.RELEASE_VERSION }}